name              'locales'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures locales'
source_url        'https://github.com/sous-chefs/locales'
issues_url        'https://github.com/sous-chefs/locales/issues'
version           '1.0.4'

supports 'ubuntu'
supports 'debian'
