name 'locales'
maintainer 'opendo GmbH'
maintainer_email 'p.bergsmann@opendo.at'
license 'Apache-2.0'
description 'Installs/Configures locales'
source_url 'https://github.com/redguide/locales'
issues_url 'https://github.com/redguide/locales/issues'
version '0.4.0'

supports 'ubuntu'
supports 'debian'
